### ISSUE TITLE
error ``height.above.ellipsoid` is not in the `Trajectory` object`

### ISSUE THREAD

**Issue by cleemansen** [kulits2/3D-BKDE#1]
Hello,

on MoveApps.org I'm facing with the following error:

```
app will be started with configuration: {'freq': '1s', 'max_seg_len': '2h', 'z_col': 'height.above.ellipsoid', 'kernel_radius': 5, 'kernel_sigma': 1, 'lat_grid_dim': 100, 'lon_grid_dim': 100, 'alt_grid_dim': 10, 'percentile': 99.5, 'show_topo': True}
storing error to /tmp/error_file.txt
Traceback (most recent call last):
  File "/opt/co-pilot-python/sdk.py", line 30, in <module>
    sdk = MoveAppsSdk(active_hooks=hooks)
  File "/opt/co-pilot-python/sdk.py", line 23, in __init__
    executor.execute()
  File "/opt/co-pilot-python/sdk/moveapps_execution.py", line 33, in execute
    raise exception
  File "/opt/co-pilot-python/sdk/moveapps_execution.py", line 29, in execute
    output = self.__call_app(data)
  File "/opt/co-pilot-python/sdk/moveapps_execution.py", line 76, in __call_app
    outputs = self._pm.hook.execute(data=data, config=self.env.app_configuration)
  File "/opt/conda/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/opt/conda/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/opt/conda/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/opt/conda/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/opt/conda/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/opt/co-pilot-python/app/app.py", line 66, in execute
    self.execute_once(data, app_config, traj_i)
  File "/opt/co-pilot-python/app/app.py", line 83, in execute_once
    assert app_config.z_col in traj.df, f"`{app_config.z_col}` is not in the `Trajectory` object"
AssertionError: `height.above.ellipsoid` is not in the `Trajectory` object
```

I'm using the following version of your app:

- Kulits, P. 2023-05-30. 3D Binned Kernel Density Estimation. version v0.2 (3). MoveApps. https://github.com/kulits2/3D-BKDE.git
- 8141d4fe2301045cf97d9386d14e0006ae1d05dd

The app gets the following input from Movebank (via _moveStack to Python_ translator):

- Study: 31987083 / Migration timing in barnacle geese (Greenland) (data from Kölzsch et al. and Shariatinajafabadi et al. 2014)
- Animals: 2 Animals (70563, 78199)
- translated files: [app-input.zip](https://github.com/kulits2/3D-BKDE/files/11597519/app-input.zip)

**Comment by cleemansen** [comment]
Okay - after opening again this issue I noticed that this is - of course - a misconfigured app on my side. My input does not have the (expected by default) attribute `height.above.ellipsoid`. So sorry for the spam!

Is there a better default field for the setting _Z Column Name_?

**Comment by kulits2** [comment]
Hi, @cleemansen. Thank you for testing the app.

As you noticed, it appears you've entered a non-existent column into `Z Column Name`. If your data has height measurements stored in another column, this parameter should be updated when instantiating the app. Note that if you are using non-ellipsoidal height data, you may want to disable the DEM display by unchecking `Show Topography` since the measurements from SRTM1 are ellipsoidal and will not be aligned with the voxels otherwise. If you don't require the DEM, the app should function with height measurements in most formats, but no transformation will be applied to standardize them.

As for a better default, I could in the future add transforms to support a wider variety of standard Movebank fields (like the height above the mean sea level), but the app currently only fully supports ellipsoidal height measurements.

Peter
